// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import externals "github.com/whiteblock/amqp/externals"
import mock "github.com/stretchr/testify/mock"

// AMQPRepository is an autogenerated mock type for the AMQPRepository type
type AMQPRepository struct {
	mock.Mock
}

// GetChannel provides a mock function with given fields:
func (_m *AMQPRepository) GetChannel() (externals.AMQPChannel, error) {
	ret := _m.Called()

	var r0 externals.AMQPChannel
	if rf, ok := ret.Get(0).(func() externals.AMQPChannel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(externals.AMQPChannel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectDelivery provides a mock function with given fields: msg, requeue
func (_m *AMQPRepository) RejectDelivery(msg externals.AMQPDelivery, requeue bool) error {
	ret := _m.Called(msg, requeue)

	var r0 error
	if rf, ok := ret.Get(0).(func(externals.AMQPDelivery, bool) error); ok {
		r0 = rf(msg, requeue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SwapConn provides a mock function with given fields: conn
func (_m *AMQPRepository) SwapConn(conn externals.AMQPConnection) {
	_m.Called(conn)
}
